import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/app/globals.css';
import {
	SidebarProvider,
	SidebarTrigger,
} from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/ui/app-sidebar';
import SearchBar from '@/components/SearchBar';

import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs';
import UserClerkMenu from '@/components/UserClerkMenu';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ClerkProvider dynamic>
					<SidebarProvider>
						<AppSidebar />

						<div className='w-full '>
							<div className='sticky top-0 w-full navBarheight  flex flex-row justify-end items-center bg-card py-4 z-[99] border-b border-border'>
								<SidebarTrigger />
								<div className='w-full flex flex-col md:flex-row items-center justify-end gap-8'>
									<span className='order-last md:order-first'>
										next game on: 31 Dec at 7:00
									</span>
									<div className='flex items-center justify-end gap-8'>
										<SearchBar />
										<UserClerkMenu />
									</div>
								</div>
							</div>
							{children}
						</div>
					</SidebarProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
